models/category.py
from app import db

class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    status = db.Column(db.String(2), default='1', nullable=False)

    def __repr__(self):
        return f'<Category {self.name}>'

controllers/admin_controller.py
from flask import Blueprint, request, jsonify,render_template,redirect,flash,url_for
from services.admin_service import get_admin_by_id, create_admin, update_admin, delete_admin
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from services import admin_service

admin_bp = Blueprint('admin', __name__)
# Import models
from models.user_model import User
from models.event_model import Event
from models.category_model import Category
from models.event_registration_model import EventRegistration
from models.favorite_model import Favorite  


@admin_bp.route('/')
@login_required
def home():
    if current_user.role != 'admin':
        flash('You are not authorized to view this page.')
        return redirect(url_for('home'))
    
    return redirect(url_for('event_management'))

@admin_bp.route('/admin/<int:admin_id>', methods=['GET'])
def get_admin(admin_id):
    admin = get_admin_by_id(admin_id)
    if admin:
        return jsonify(admin), 200
    return jsonify({"error": "Admin not found"}), 404

@admin_bp.route('/admin/add_admin', methods=['POST'])
def add_admin():
    data = request.json
    new_admin = create_admin(data['name'], data['login'], data['password'])
    return jsonify(new_admin), 201

@admin_bp.route('/admin/<int:admin_id>', methods=['PUT'])
def update_admin_info(admin_id):
    data = request.json
    updated_admin = update_admin(
        admin_id,
        name=data.get('name'),
        login=data.get('login'),
        password=data.get('password'),
        status=data.get('status')
    )
    if updated_admin:
        return jsonify(updated_admin), 200
    return jsonify({"error": "Admin not found"}), 404

@admin_bp.route('/admin/<int:admin_id>', methods=['DELETE'])
def delete_admin_info(admin_id):
    deleted_admin = delete_admin(admin_id)
    if deleted_admin:
        return jsonify({"message": "Admin deleted successfully"}), 200
    return jsonify({"error": "Admin not found"}), 404


@admin_bp.route('/calendar_events')
def calendar_events():
    rows = admin_service.query_workshop_cal()
    
    resp = jsonify({'success' : 1, 'result' : rows })	# 转化为，，，便于数据展示
    resp.status_code = 200
    return resp
   

@admin_bp.route('/event_management', methods=['GET'])
def event_management():
    # 获取当前页码
    page = request.args.get('page', 1, type=int)
    per_page = 10  # 每页显示10条记录

    # 构建查询语句
    event_sql = "SELECT * FROM events where status = 0"
    total_sql = "SELECT COUNT(*) AS total_count FROM events where status = 0"

    # 使用分页函数获取数据和分页信息
    events, pagination = admin_service.paginate_results(total_sql, event_sql, page, per_page)

    # 获取所有分类
    categories = admin_service.get_all_categories()

    # 渲染模板，并将分页数据传递给模板
    return render_template("admin/event/event_list.html", events=events, categories=categories, pagination=pagination)


@admin_bp.route('/cancel_event', methods=['POST'])
def cancel_event():
    data = request.json
    event_id = data.get('event_id')
    status = data.get('status')
    admin_service.cancel_event(event_id,status)
   
    return jsonify({"message": "Event status updated successfully"}), 200


@admin_bp.route('/filter_events', methods=['GET', 'POST'])
def filter_events():
    page = request.args.get('page', 1, type=int)  # 获取当前页码
    per_page = 10  # 每页显示的记录数
    
    search = request.form.get('search')
    filter_type = request.form.get('filter')
    category = request.form.get('category')

    # 构建查询语句
    query = "SELECT * FROM events WHERE 1=1 and status = 0 "
    
    if search:
        if filter_type == 'location':
            query += f" AND location LIKE '%{search}%'"
        elif filter_type == 'date':
            query += f" AND date LIKE '%{search}%'"
    
    if category:
        query += f" AND category_id = '{category}'"

    # 获取总记录数的SQL
    total_sql = "SELECT COUNT(*) AS total_count FROM events WHERE 1=1 and status = 0 "
    if search:
        if filter_type == 'location':
            total_sql += f" AND location LIKE '%{search}%'"
        elif filter_type == 'date':
            total_sql += f" AND date LIKE '%{search}%'"
    
    if category:
        total_sql += f" AND category_id = '{category}'"
    
    # 调用分页函数
    events, pagination = admin_service.paginate_results(total_sql, query, page, per_page)
    
    categories = admin_service.get_all_categories()
    
    return render_template('admin/event/event_list.html', 
                           events=events, 
                           categories=categories, 
                           pagination=pagination)


@admin_bp.route('/event_detail/<int:id>', methods=(['GET','POST']))
def event_detail(id):
    event_detail = admin_service.get_event(id)
    return render_template('admin/event/event_detail.html', event=event_detail)


@admin_bp.route('/edit_event/<int:id>', methods=['GET','POST'])
def edit_event(id):
    categories = admin_service.get_all_categories()
    event = admin_service.get_event(id)
    if request.method == 'POST':
        name = request.form['name']
        description=request.form['description']
        location=request.form['location']
        date=request.form['date']
        end_date=request.form['end_date']
        intro = request.form['intro']
        category_id=request.form['category_id']
        image = request.files['images']
        img = request.form['image']
        if image:
            image.save('static/images/event/' + image.filename)
            image_name= '/static/images/event/'+ image.filename
        else:
            image_name = img
        admin_service.edit_event(id,name, description, location, date,end_date,category_id,intro,image_name)
        flash("Created event successful")
        return redirect(url_for('admin.event_management'))
    return render_template("admin/event/edit_event.html",categories=categories,event=event)

controllers/category_controller.py
from flask import Blueprint, request, jsonify,render_template,flash,redirect,url_for
from services import category_service
from flask_login import current_user
category_bp = Blueprint('category', __name__)

@category_bp.route('/category_management', methods=['GET'])
def category_management():
    categories = category_service.get_all_categories()
    if current_user.role != 'admin':
        return render_template("front/category/category_list.html",categories=categories) 
    else:
        return render_template("admin/category/category_list.html",categories=categories) 

@category_bp.route('/create_category', methods=['GET','POST'])
def create_category():
    if request.method == 'POST':
        name = request.form['name']
        category_service.create_category(name)
        flash("create category successful")
        return redirect(url_for('category.category_management'))
    if current_user.role != 'admin':
        return render_template("front/category/create_category.html")
    else:
        return render_template("admin/category/create_category.html")

@category_bp.route('/edit_category/<int:id>', methods=['GET','POST'])
def edit_category(id):
    id = id
    category = category_service.get_category_by_id(id)
    if request.method == 'POST':
        name = request.form['name']
       
        category_service.update_category(id,name)
        flash("edit category successful")
        return redirect(url_for('category.category_management'))
    if current_user.role != 'admin':
        return render_template("front/category/edit_category.html",category=category)
    else:
        return render_template("admin/category/edit_category.html",category=category)

@category_bp.route('/delete_category', methods=['POST'])  
def delete_category():
    data = request.json  # 获取从前端传递的数据
    category_id = data.get('id')  # 提取类别ID
    category_service.delete_category(category_id)
    return jsonify({'success': True}), 200

templates/front/category/category_list.html
{% extends "front/base.html" %}

{% block title %}Admin Dashboard - Community Event Planner{% endblock %}
{% block content %}


<section id="banner" style="background-image:url(images/background-img.jpg);">
    <div class="container padding-medium-2">
        <div class="hero-content ">
            <h2 class="display-2 fw-semibold"><span class="text-primary">Categories</span> </h2>
            <nav class="breadcrumb">
                <a class="breadcrumb-item text-muted nav-link" href="{{url_for('admin.home')}}">Home</a>
                
                <span class="breadcrumb-item active" aria-current="page">Categories</span>
            </nav>
        </div>
    </div>
</section>

<section id="course" class="padding-medium">
    <div class="container">
        <div class="mb-5 mt-5 mt-lg-0">
            <h2 class="display-5 fw-semibold">  <span class="text-primary">Category List</span></h2>
            
          </div>
        <div class="row">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Category Name</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in categories %}
                    <tr>
                        <td>{{ c.name }}</td>
                        <td>
                            <a href="{{ url_for('category.edit_category', id=c.id) }}">Edit</a> 
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
        </div>
    </div>
</section>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var deleteLinks = document.querySelectorAll('.delete-category-link');
    
        deleteLinks.forEach(function(link) {
            link.addEventListener('click', function(event) {
                event.preventDefault(); // 防止默认链接跳转行为
                
                var categoryId = this.getAttribute('data-id');
                var confirmed = confirm("Are you sure you want to delete this category?");
                
                if (confirmed) {
                    // 使用 AJAX 发送删除请求
                    var xhr = new XMLHttpRequest();
                    xhr.open('POST', "{{ url_for('category.delete_category') }}", true);
                    xhr.setRequestHeader('Content-Type', 'application/json;charset=UTF-8');
                    xhr.onreadystatechange = function() {
                        if (xhr.readyState === XMLHttpRequest.DONE) {
                            if (xhr.status === 200) {
                                alert("Category deleted successfully.");
                                location.reload();  // 删除成功后刷新页面或更新 UI
                            } else {
                                alert("An error occurred while trying to delete the category.");
                            }
                        }
                    };
                    
                    xhr.send(JSON.stringify({ id: categoryId }));
                }
            });
        });
    });
    </script>
{% endblock %}

templates/front/category/create_category.html
{% extends "front/base.html" %}

{% block title %}Admin Dashboard - Community Event Planner{% endblock %}
{% block content %}


<section id="banner" style="background-image:url(/static/images/background-img.jpg);">
    <div class="container padding-medium-2">
        <div class="hero-content ">
            <h2 class="display-2 fw-semibold">Create New Category</h2>
            <nav class="breadcrumb">
                <a class="breadcrumb-item text-muted nav-link" href="{{url_for('admin.home')}}">Home</a>
                
                <span class="breadcrumb-item active" aria-current="page">Category</span>
            </nav>
        </div>
    </div>
</section>
<section id="register">
    <div class="container-fluid">
      <div class="row align-items-center">
        <div class="col-md-6 ">
          <img src="/static/images/bg1.jpeg" alt="img" class="img-fluid">
        </div>
        <div class="col-md-4 ">
          <div class="mb-5 mt-5 mt-lg-0">
            <h2 class="display-5 fw-semibold"> Create <span class="text-primary">New Category</span></h2>
            
          </div>
          <form id="form" action="{{ url_for('category.create_category') }}" method="post">
            <label>Category Name</label>
            <input type="text" name="name" placeholder="Write category Name*" class="form-control w-100 mb-4">
            <button class="btn btn-primary px-5 py-3 mt-2" type="submit"> Submit</button>
          </form>

        </div>

      </div>
    </div>
  </section>

{% endblock %}

templates/front/category/edit_category.html
{% extends "front/base.html" %}

{% block title %}Admin Dashboard - Community Event Planner{% endblock %}
{% block content %}


<section id="banner" style="background-image:url(/static/images/background-img.jpg);">
    <div class="container padding-medium-2">
        <div class="hero-content ">
            <h2 class="display-2 fw-semibold">Edit Category</h2>
            <nav class="breadcrumb">
                <a class="breadcrumb-item text-muted nav-link" href="{{url_for('admin.home')}}">Home</a>
                
                <span class="breadcrumb-item active" aria-current="page">Category</span>
            </nav>
        </div>
    </div>
</section>
<section id="register">
    <div class="container-fluid">
      <div class="row align-items-center">
        <div class="col-md-6 ">
          <img src="/static/images/bg1.jpeg" alt="img" class="img-fluid">
        </div>
        <div class="col-md-4 ">
          <div class="mb-5 mt-5 mt-lg-0">
            <h2 class="display-5 fw-semibold"> Edit <span class="text-primary">Category</span></h2>
            
          </div>
          <form id="form" action="{{ url_for('category.edit_category',id =category.id) }}" method="post">
            <label>Category Name</label>
            <input type="text" name="name" value="{{category.name}}" class="form-control w-100 mb-4">
           
            <button class="btn btn-primary px-5 py-3 mt-2" type="submit"> Submit</button>
          </form>

        </div>

      </div>
    </div>
  </section>

{% endblock %}