controllers/category_controller.py
from flask import Blueprint, request, jsonify,render_template,flash,redirect,url_for
from services import category_service
from flask_login import current_user
category_bp = Blueprint('category', __name__)

@category_bp.route('/category_management', methods=['GET'])
def category_management():
    categories = category_service.get_all_categories()
    if current_user.role != 'admin':
        return render_template("front/category/category_list.html",categories=categories) 
    else:
        return render_template("admin/category/category_list.html",categories=categories) 

@category_bp.route('/create_category', methods=['GET','POST'])
def create_category():
    if request.method == 'POST':
        name = request.form['name']
        category_service.create_category(name)
        flash("create category successful")
        return redirect(url_for('category.category_management'))
    if current_user.role != 'admin':
        return render_template("front/category/create_category.html")
    else:
        return render_template("admin/category/create_category.html")

@category_bp.route('/edit_category/<int:id>', methods=['GET','POST'])
def edit_category(id):
    id = id
    category = category_service.get_category_by_id(id)
    if request.method == 'POST':
        name = request.form['name']
       
        category_service.update_category(id,name)
        flash("edit category successful")
        return redirect(url_for('category.category_management'))
    if current_user.role != 'admin':
        return render_template("front/category/edit_category.html",category=category)
    else:
        return render_template("admin/category/edit_category.html",category=category)

@category_bp.route('/delete_category', methods=['POST'])  
def delete_category():
    data = request.json  # 获取从前端传递的数据
    category_id = data.get('id')  # 提取类别ID
    category_service.delete_category(category_id)
    return jsonify({'success': True}), 200

controllers/event_controller.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, flash
from flask_login import login_required, current_user
from services import event_service 
from models.event_model import Event  
from app import db
from config import setting
from models.event_registration_model import EventRegistration

event_bp = Blueprint('event', __name__)





@event_bp.route('/event_management', methods=['GET'])
@login_required
def event_management():
    page = request.args.get('page', 1, type=int)
    category = request.args.get('category', '')
    search = request.args.get('search', '')
    filter_type = request.args.get('filter', '')
    user_id = current_user.id

    # 构建基础查询语句
    base_query = f"""
    SELECT 
    e.*,
    CASE 
        WHEN e.author_id = '{user_id}' THEN 1
        WHEN er.user_id = '{user_id}' THEN 2
        ELSE 0
    END AS if_my,
    CASE 
        WHEN f.event_id IS NOT NULL THEN 1
        ELSE 0
    END AS if_f
FROM 
    events e
LEFT JOIN 
    event_registrations er ON e.id = er.event_id AND er.user_id = '{user_id}'
LEFT JOIN 
    favorites f ON e.id = f.event_id AND f.user_id = '{user_id}'  -- 加入判断是否在favorite表中
WHERE 
    1=1 and e.status = 0
    """
    total_sql = f"""SELECT COUNT(*) AS total_count FROM ({base_query}) AS total"""

    # 添加搜索和过滤条件
    if search:
        if filter_type == 'location':
            base_query += " AND e.location LIKE '%{}%'".format(search)
        elif filter_type == 'date':
            base_query += " AND e.date LIKE '%{}%'".format(search)

    if category:
        base_query += " AND e.category_id = {}".format(category)

    # 添加排序条件
    base_query += " ORDER BY e.id DESC"

    # 使用分页方法
    items, pagination = event_service.paginate_results(total_sql, base_query, page, 20)

    return render_template('front/event/event_list.html', events=items, categories=event_service.get_categories(), pagination=pagination)




@event_bp.route('/event_detail/<int:id>', methods=['GET'])
@login_required
def event_detail(id):
    event = event_service.get_event_by_id(id,current_user.id)
    return render_template("front/event/event_detail.html",event = event)


@event_bp.route('/create_event', methods=['GET','POST'])
@login_required
def create_event():
    categories = event_service.get_categories()
    if request.method == 'POST':
        name = request.form['name']
        description=request.form['description']
        location=request.form['location']
        date=request.form['date']
        end_date=request.form['end_date']
        intro = request.form['intro']
        category_id=request.form['category_id']
        image = request.files['image']
       
        if image:
            image.save('static/images/event/' + image.filename)
            image_name= '/static/images/event/'+ image.filename
        else:
            image_name = setting.default_image
        event_service.create_event(name, description, location, date,end_date,category_id,intro,image_name,current_user.id)
        flash("Created event successful")
        return redirect(url_for('event.event_management'))
    return render_template("front/event/create_event.html",categories=categories)



@event_bp.route('/edit_event/<int:id>', methods=['GET','POST'])
@login_required
def edit_event(id):
    categories = event_service.get_categories()
    event = event_service.get_event_by_id(id,current_user.id)
    if request.method == 'POST':
        name = request.form['name']
        description=request.form['description']
        location=request.form['location']
        date=request.form['date']
        end_date=request.form['end_date']
        intro = request.form['intro']
        category_id=request.form['category_id']
        
        image = request.files['image']
        if image:
            image.save('static/images/event/' + image.filename)
            image_name= '/static/images/event/'+ image.filename
        else:
            image_name = setting.default_image
        event_service.update_event(name, description, location, date,end_date,category_id,intro,image_name,id)
        return redirect(url_for('event.event_management'))
    return render_template("front/event/edit_event.html",event = event,categories=categories)

@event_bp.route('/event/<int:event_id>', methods=['PUT'])
def update_event_info(event_id):
    data = request.json
    updated_event = event_service.update_event(
        event_id,
        name=data.get('name'),
        description=data.get('description'),
        location=data.get('location'),
        date=data.get('date'),
        category_id=data.get('category_id')
    )
    if updated_event:
        return jsonify(updated_event.serialize()), 200
    return jsonify({"error": "Event not found"}), 404

@event_bp.route('/event/<int:event_id>', methods=['DELETE'])
def delete_event_info(event_id):
    deleted_event = event_service.delete_event(event_id)
    if deleted_event:
        return jsonify({"message": "Event deleted successfully"}), 200
    return jsonify({"error": "Event not found"}), 404



@event_bp.route('/favorite_event', methods=['GET'])
@login_required
def favorite_event():
    categories = event_service.get_categories()
    page = request.args.get('page', 1, type=int)
    category = request.args.get('category', '')
    search = request.args.get('search', '')
    filter_type = request.args.get('filter', '')
    user_id = current_user.id

    # 构建基础查询语句
    base_query = f"""
    SELECT 
        e.*
    FROM 
        events e
    JOIN 
        favorites f ON e.id = f.event_id AND f.user_id = '{user_id}'
    WHERE 
        e.author_id != '{user_id}' and e.status = 0
    """

    # 构建计算总记录数的查询
    total_sql = f"""SELECT COUNT(*) AS total_count FROM ({base_query}) AS total"""

    # 添加搜索和过滤条件
    if search:
        if filter_type == 'location':
            base_query += f" AND e.location LIKE '%{search}%'"
        elif filter_type == 'date':
            base_query += f" AND e.date LIKE '%{search}%'"

    if category:
        base_query += f""" AND e.category_id = '{category}'"""

    # 添加排序条件
    base_query += " ORDER BY e.id DESC"

    # 使用分页方法
    items, pagination = event_service.paginate_results(total_sql, base_query, page, 12)

    return render_template('front/event/favorite_event.html', events=items, categories=categories, pagination=pagination)


@event_bp.route('/event_register/<int:id>', methods=['POST'])
@login_required 
def event_register(id):
    event = Event.query.get_or_404(id) 
    if event:
        registration = EventRegistration(user_id=current_user.id, event_id=event.id)
        db.session.add(registration)
        db.session.commit()
        flash('Successfully registered for the event!')
        return redirect(url_for('event_bp.event_detail', event_id=event.id))
    flash('Event not found!')
    return redirect(url_for('home'))



@event_bp.route('/quit_event', methods=['POST'])
@login_required
def quit_event():
    data = request.json
    event_id = data.get('event_id')
    event_service.delete_register(event_id, current_user.id)
    return jsonify({'success': True}), 200

@event_bp.route('/add_favorite/<int:id>', methods=['POST'])
@login_required
def add_favorite(id):
   
    event_service.add_favorite(id, current_user.id)
    return jsonify({'success': True}), 200

@event_bp.route('/delete_favorite/<int:id>', methods=['POST'])
@login_required
def delete_favorite(id):
   
    event_service.delete_favorite(id, current_user.id)
    return jsonify({'success': True}), 200

@event_bp.route('/join_event', methods=['POST'])
@login_required
def join_event():
    data = request.json
    event_id = data.get('event_id')
    event_service.add_register(event_id, current_user.id)
    return jsonify({'success': True}), 200



@event_bp.route('/offline/<int:id>', methods=['POST'])
@login_required
def offline(id):
   
    event_service.update_event_status(id,1)
    return jsonify({'success': True}), 200

@event_bp.route('/online/<int:id>', methods=['POST'])
@login_required
def online(id):
    event_service.update_event_status(id,0)
    return jsonify({'success': True}), 200


@event_bp.route('/my_event', methods=['GET'])
@login_required
def my_event():
    categories = event_service.get_categories()
    page = request.args.get('page', 1, type=int)
    category = request.args.get('category', '')
    search = request.args.get('search', '')
    filter_type = request.args.get('filter', '')
    user_id = current_user.id  # 使用 Flask-Login 获取当前用户ID

    # 构建基础查询语句
    base_query = f"""
    SELECT 
        e.*
    FROM 
        events e
    WHERE 
        e.author_id = '{user_id}' and e.status = 0
    """

    # 构建计算总记录数的查询
    total_sql = f"""SELECT COUNT(*) AS total_count FROM ({base_query}) AS total"""

    # 添加搜索和过滤条件
    if search:
        if filter_type == 'location':
            base_query += f" AND e.location LIKE '%{search}%'"
        elif filter_type == 'date':
            base_query += f" AND e.date LIKE '%{search}%'"

    if category:
        base_query += f""" AND e.category_id = '{category}'"""

    # 添加排序条件
    base_query += " ORDER BY e.id DESC"

    # 使用分页方法
    items, pagination = event_service.paginate_results(total_sql, base_query, page, 12)

    return render_template('front/event/my_event.html', events=items, categories=categories, pagination=pagination)



@event_bp.route('/event_schedule')
@login_required
def event_schedule():
    return render_template('front/event/event_dashboard.html')



@event_bp.route('/calendar_events')
def calendar_events():
    rows = event_service.query_workshop_cal()
   
    resp = jsonify({'success' : 1, 'result' : rows })	# 转化为，，，便于数据展示
    resp.status_code = 200
    return resp

templates/front/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="format-detection" content="telephone=no">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="author" content="">
  <meta name="keywords" content="">
  <meta name="description" content="">
</head>

<link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/Swiper/9.4.1/swiper-bundle.min.css" />

<link rel="stylesheet" type="text/css" href="/static/icomoon/icomoon.css">

<link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.3.0-alpha3/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="/static/css/vendor.css">
<link rel="stylesheet" type="text/css" href="/static/css/style.css">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Jost:wght@400;600;700&family=Roboto+Slab&display=swap"
  rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<body>

  <nav class="main-menu d-flex navbar fixed-top navbar-expand-lg p-2 py-3 p-lg-4 py-lg-4 ">
    <div class="container-fluid">
      <div class="main-logo">
        <a href="{{ url_for('home') }}">
          <img src="/static/images/logo.png" alt="logo" class="img-fluid">
        </a>
      </div>

      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
        aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">

        <div class="offcanvas-header">
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>

        <div class="offcanvas-body justify-content-end">

          <ul class="navbar-nav menu-list list-unstyled align-items-lg-center d-flex gap-md-3 mb-0">
            <li class="nav-item">
              <a href="{{ url_for('home') }}" class="nav-link mx-2 active">Home</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link mx-2 dropdown-toggle align-items-center" role="button" id="events"
                data-bs-toggle="dropdown" aria-expanded="false">events</a>
              <ul class="dropdown-menu" aria-labelledby="courses">
                
                <li><a href="{{ url_for('event.event_management') }}" class="dropdown-item">event</a></li>
                <li><a href="{{ url_for('event.create_event') }}" class="dropdown-item">create event</a></li>
                <li><a href="{{ url_for('event.favorite_event') }}" class="dropdown-item">my favorite</a></li>
                <li><a href="{{ url_for('event.my_event') }}" class="dropdown-item">my event</a></li>   
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link mx-2 dropdown-toggle align-items-center" role="button" id="courses"
                  data-bs-toggle="dropdown" aria-expanded="false">Category</a>
              <ul class="dropdown-menu" aria-labelledby="courses">
                  <li><a href="{{ url_for('category.category_management') }}"
                          class="dropdown-item">Category Management</a></li>
                  <li><a href="{{ url_for('category.create_category') }}" class="dropdown-item">Create
                          Category </a></li>
              </ul>
          </li>
            <li class="nav-item">
              <a href="{{url_for('contact')}}" class="nav-link mx-2">contact</a>
            </li>
            <li class="nav-item">
              <a href="{{url_for('about')}}" class="nav-link mx-2 text-decoration-underline">About</a>
            </li>
          </ul>

          <div class="d-none d-lg-flex align-items-center ms-5">
            <ul class="d-flex justify-content-end  list-unstyled m-0">
              {% if current_user.is_authenticated %}
              <li>
                <a class="btn btn-outline-dark mx-3 p-3" href="{{ url_for('profile') }}">Profile</a>
              </li>
              <li>
                <a class="btn btn-outline-dark mx-3 p-3" href="{{ url_for('logout') }}">Logout</a>
              </li>
              {% else %}
              <li>
                <a class="btn btn-outline-dark mx-3 p-3" href="{{ url_for('login') }}">Login</a>
              </li>
              <li>
                <a class="btn btn-outline-dark mx-3 p-3" href="{{ url_for('register') }}">Register</a>
              </li>
              {% endif %}

            </ul>

          </div>

        </div>
      </div>

    </div>
  </nav>

  <!-- Main Content Area -->

  {% block content %}{% endblock %}


  {% for category, message in get_flashed_messages(with_categories=true) %}
  <div class="flash" id="flash-message">{{ message }}</div>
  {% endfor %}
  <footer id="footer">
    <div class="container padding-medium ">
      <div class="row">
        <div class="col-md-4 my-3">
          <h5 class="text-uppercase fw-bold mb-4">Contact us</h5>
          <p><iconify-icon class="social-icon text-primary fs-5 me-2" icon="mdi:location"
            style="vertical-align:text-bottom"></iconify-icon> <span class="fw-bold">Address: </span> 730 Glenstone Ave 65802,
            Springfield, US</p>
          <p><iconify-icon class="social-icon text-primary fs-5 me-2" icon="solar:phone-bold"
            style="vertical-align:text-bottom"></iconify-icon> <span class="fw-bold">Phone: </span> (123) 000-321
          </p>
          <p><iconify-icon class="social-icon text-primary fs-5 me-2" icon="ic:baseline-email"style="vertical-align:text-bottom"></iconify-icon> <span class="fw-bold">Email: </span>
            contactoffice@website.com              
          </p>
        </div>
        <div class="col-md-2 my-3">
          <div class="footer-menu">
            <h5 class="text-uppercase fw-bold mb-4">Links</h5>
            <ul class="menu-list list-unstyled">
              <li class="menu-item mb-2">
                <a href="#" class="footer-link">Home</a>
              </li>
              <li class="menu-item mb-2">
                <a href="#" class="footer-link">About us</a>
              </li>
              <li class="menu-item mb-2">
                <a href="#" class="footer-link">Courses</a>
              </li>
              <li class="menu-item mb-2">
                <a href="#" class="footer-link">Blogs</a>
              </li>
              <li class="menu-item mb-2">
                <a href="#" class="footer-link">Contact</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 my-3">
          <div class="footer-menu">
            <h5 class="text-uppercase fw-bold mb-4">support</h5>
            <ul class="menu-list list-unstyled">
              <li class="menu-item mb-2">
                <a href="#">FAQs</a>
              </li>
              <li class="menu-item mb-2">
                <a href="#">Support</a>
              </li>
            </ul>
          </div>
        </div>

      </div>
    </div>
    </div>
  </footer>

  <div id="footer-bottom">
    <hr class="m-0 text-black-50">
    <div class="container py-3">
      <div class="row mt-3">
        <div class="col-md-6 copyright">
          <p>© Developed By Yang Hua</p>
        </div>

      </div>
    </div>
  </div>


  <script src="/static/js/jquery-1.11.0.min.js"></script>
  <script src="https://cdn.bootcdn.net/ajax/libs/Swiper/9.4.1/swiper-bundle.min.js"></script>
  <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.3.0-alpha3/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
    crossorigin="anonymous"></script>
  <script src="/static/js/plugins.js"></script>
  <script src="/static/js/script.js"></script>
  <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
</body>
<script>
  // 在页面加载后，8 秒后隐藏 Flash 消息
  window.onload = function () {
    setTimeout(function () {
      var flashMessage = document.getElementById('flash-message');
      flashMessage.style.display = 'none';
    }, 5000); // 5 秒后隐藏
  };



</script>
<style>
  .flash {
    background-color: #ffcc00;
    color: #333;
    border: 1px solid #ffcc00;
    padding: 20px;
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 1000;
  }
</style>

</html>

templates/front/home.html
{% extends 'front/base.html' %}

{% block title %}Home - Community Event Planner{% endblock %}

{% block content %}
<section id="hero">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 col-lg-3 offset-md-2 padding-large ps-lg-0 pe-lg-5">
        <h2 class="display-2 fw-semibold">Great Event Planner Platform</h2>
        <p class="secondary-font my-4 pb-2">Community Event Planner</p>

      </div>
      <div class="col-md-6 col-lg-7 d-block d-md-none d-lg-block p-0">
        <img src="/static/images/billboard-img.jpg" alt="img" class="img-fluid">
      </div>
    </div>
  </div>
</section>
<section id="top-sell" class="padding-medium">
  <div class="container">

    <div class="text-center mb-5">
      <h2 class="display-5 fw-semibold">Check <span class="text-primary">Events</span></h2>

    </div>

    <div class="text-center mb-3">
      <p class="m-0">
        <button class="filter-button px-3 py-2 mt-2 rounded-pill me-4  active" data-filter="*">All</button>
        <button class="filter-button px-3 py-2 mt-2 rounded-pill me-4 " data-filter=".digital">My Events</button>
        <button class="filter-button px-3 py-2 mt-2 rounded-pill me-4 " data-filter=".web">MY Joined Events</button>
        <button class="filter-button px-3 py-2 mt-2 rounded-pill me-4 " data-filter=".tech">MY Favorite</button>

      </p>
    </div>

    <div class="isotope-container row">
      {% for event in events %}

      <div class="item digital col-md-4 col-lg-3 my-5">
        <div class="card position-relative">
          <img src="{{event.img}}" class="img-fluid rounded-3" alt="image">
          <div class="card-body p-0">

            <span class="badge text-muted bg-success mt-3 mb-1">feature</span>

            <a href="{{ url_for('event.event_detail',id=event.id) }}">
              <h5 class="py-2 m-0">{{ event.name }}</h5>
            </a>

            <div class="card-text">


              <h4 class=" text-primary">{{ event.date }} <span class="fs-6 text-black opacity-25">{{ event.location
                  }}</span></h4>

              <div class="d-flex flex-wrap mt-2">
                {%if event.if_my == 1 %}
                <a href="{{ url_for('event.event_detail',id=event.id) }}"
                  class=" btn btn-outline-dark text-capitalize me-2 px-4 py-3">Manage</a>
                {%else%}
                <a href="{{ url_for('event.event_detail',id=event.id) }}"
                  class=" btn btn-outline-dark text-capitalize me-2 px-4 py-3">View</a>

                {%endif%}
              </div>

            </div>
          </div>
        </div>
      </div>
      {% endfor %}
      {% for event in my_events %}
      <div class="item web col-md-4 col-lg-3 my-5">


        <div class="card position-relative">
          <img src="{{event.img}}" class="img-fluid rounded-3" alt="image">
          <div class="card-body p-0">

            <span class="badge text-muted bg-success mt-3 mb-1">feature</span>

            <a href="{{ url_for('event.event_detail',id=event.id) }}">
              <h5 class="py-2 m-0">{{ event.name }}</h5>
            </a>

            <div class="card-text">


              <h4 class=" text-primary">{{ event.date }} <span class="fs-6 text-black opacity-25">{{
                  event.location}}</span></h4>

              <div class="d-flex flex-wrap mt-2">
                <a href="#" onclick="quitEvent({{ event.id }})"
                  class=" btn btn-outline-dark text-capitalize me-2 px-4 py-3">Quit Join</a>

              </div>

            </div>

          </div>
        </div>

      </div>
      {% endfor %}
      {% for event in my_favorite %}
      <div class="item tech col-md-4 col-lg-3 my-5">


        <div class="card position-relative">
          <img src="{{event.img}}" class="img-fluid rounded-3" alt="image">
          <div class="card-body p-0">

            <span class="badge text-muted bg-success mt-3 mb-1">feature</span>

            <a href="{{ url_for('event.event_detail',id=event.id) }}">
              <h5 class="py-2 m-0">{{ event.name }}</h5>
            </a>

            <div class="card-text">


              <h4 class=" text-primary">{{ event.date }} <span class="fs-6 text-black opacity-25">{{ event.location
                  }}</span></h4>

              <div class="d-flex flex-wrap mt-2">

                <a href="#" onclick="deleteFavorite({{ event.id }})" class="btn btn-outline-dark text-capitalize">
                  <iconify-icon icon="mdi:heart" class="fs-5 pt-1"></iconify-icon>
                </a>
              </div>

            </div>

          </div>
        </div>

      </div>
      {% endfor %}

    </div>


  </div>
</section>
<script>
  function quitEvent(eventId) {
    $.ajax({
      url: "{{ url_for('event.quit_event') }}",  // Flask 视图的 URL
      type: "POST",
      contentType: "application/json",
      data: JSON.stringify({ "event_id": eventId }),  // 发送事件 ID
      success: function (response) {
        if (response.success) {
          alert('You have successfully quit the event.');
          // 更新页面状态，例如按钮变为 "Join Now"
        } else {
          alert('Failed to quit the event.');
        }
      },
      error: function (xhr, status, error) {
        console.error('Error quitting event:', error);
        alert('Failed to quit the event.');
      }
    });
  };
  function joinEvent(eventId) {
    $.ajax({
      url: "{{ url_for('event.join_event') }}",  // Flask 视图的 URL
      type: "POST",
      contentType: "application/json",
      data: JSON.stringify({ "event_id": eventId }),  // 发送事件 ID
      success: function (response) {
        if (response.success) {
          alert('You have successfully joined the event.');
          // 更新页面状态，例如按钮变为 "Quit"
        } else {
          alert('Failed to join the event.');
        }
      },
      error: function (xhr, status, error) {
        console.error('Error joining event:', error);
        alert('Failed to join the event.');
      }
    });
  };
  
</script>
{% endblock %}

templates/front/login.html
{% extends 'front/base.html' %}

{% block title %}Login - Community Event Planner{% endblock %}

{% block content %}


<div class="modal-dialog" style="max-width: 500px;">
  <div class="modal-content">

    <div class="modal-body">
      <div class="tabs-listing mt-4">
        <nav>
          <div class="nav nav-tabs d-flex justify-content-center border-0" id="nav-tab" role="tablist">
            <button class="btn btn-outline-primary px-5 py-3 me-3 active" id="nav-sign-in-tab" data-bs-toggle="tab"
              data-bs-target="#nav-sign-in" type="button" role="tab" aria-controls="nav-sign-in"
              aria-selected="true">Log In</button>
          </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
          <div class="tab-pane fade active show" id="nav-sign-in" role="tabpanel" aria-labelledby="nav-sign-in-tab">
            <form method="POST" action="{{url_for('login')}}" class="form-group flex-wrap p-3 ">
              <div class="form-input col-lg-12 my-4">
                <label for="exampleInputEmail1"
                  class="form-label fs-6 text-uppercase fw-bold text-black">Username:</label>
                <input type="text" id="username" name="username" class="form-control" required autocapitalize="off">
              </div>
              <div class="form-input col-lg-12 my-4">
                <label for="inputPassword1" class="form-label  fs-6 text-uppercase fw-bold text-black">Password</label>
                <input type="password" id="password" name="password" class="form-control" required>


              </div>

              <div class="d-grid my-3">
                <button class="btn btn-primary px-5 py-3">Log In</button>
              </div>
            </form>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/front/profile.html
{% extends 'base.html' %}

{% block title %}Profile - Community Event Planner{% endblock %}

{% block content %}
    <h1 class="mb-4">Edit Profile</h1>
    <form method="POST">
        <div class="mb-3">
            <label for="name" class="form-label">Name:</label>
            <input type="text" id="name" name="name" value="{{ current_user.name }}" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="pic" class="form-label">Profile Picture URL:</label>
            <input type="text" id="pic" name="pic" value="{{ current_user.pic }}" class="form-control">
        </div>
        <div class="mb-3">
            <label for="desc" class="form-label">Description:</label>
            <textarea id="desc" name="desc" class="form-control">{{ current_user.desc }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
{% endblock %}

templates/front/register.html
{% extends 'front/base.html' %}

{% block title %}Register - Community Event Planner{% endblock %}

{% block content %}
    <h1 class="mb-4">Register</h1>
    <form method="POST">
        <div class="mb-3">
            <label for="username" class="form-label">Username:</label>
            <input type="text" id="username" name="username" class="form-control" required autocapitalize="off">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password:</label>
            <input type="password" id="password" name="password" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="confirm_password" class="form-label">Confirm Password:</label>
            <input type="password" id="confirm_password" name="confirm_password" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="role" class="form-label">Role:</label>
            <select id="role" name="role" class="form-select">
                <option value="user">User</option>
                <option value="admin">Admin</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
{% endblock %}