controllers/admin_controller.py
from flask import Blueprint, request, jsonify,render_template,redirect,flash,url_for
from services.admin_service import get_admin_by_id, create_admin, update_admin, delete_admin
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from services import admin_service

admin_bp = Blueprint('admin', __name__)
# Import models
from models.user_model import User
from models.event_model import Event
from models.category_model import Category
from models.event_registration_model import EventRegistration
from models.favorite_model import Favorite  


@admin_bp.route('/')
@login_required
def home():
    if current_user.role != 'admin':
        flash('You are not authorized to view this page.')
        return redirect(url_for('home'))
    
    return redirect(url_for('event_management'))

@admin_bp.route('/admin/<int:admin_id>', methods=['GET'])
def get_admin(admin_id):
    admin = get_admin_by_id(admin_id)
    if admin:
        return jsonify(admin), 200
    return jsonify({"error": "Admin not found"}), 404

@admin_bp.route('/admin/add_admin', methods=['POST'])
def add_admin():
    data = request.json
    new_admin = create_admin(data['name'], data['login'], data['password'])
    return jsonify(new_admin), 201

@admin_bp.route('/admin/<int:admin_id>', methods=['PUT'])
def update_admin_info(admin_id):
    data = request.json
    updated_admin = update_admin(
        admin_id,
        name=data.get('name'),
        login=data.get('login'),
        password=data.get('password'),
        status=data.get('status')
    )
    if updated_admin:
        return jsonify(updated_admin), 200
    return jsonify({"error": "Admin not found"}), 404

@admin_bp.route('/admin/<int:admin_id>', methods=['DELETE'])
def delete_admin_info(admin_id):
    deleted_admin = delete_admin(admin_id)
    if deleted_admin:
        return jsonify({"message": "Admin deleted successfully"}), 200
    return jsonify({"error": "Admin not found"}), 404


@admin_bp.route('/calendar_events')
def calendar_events():
    rows = admin_service.query_workshop_cal()
    
    resp = jsonify({'success' : 1, 'result' : rows })	# 转化为，，，便于数据展示
    resp.status_code = 200
    return resp
   

@admin_bp.route('/event_management', methods=['GET'])
def event_management():
    # 获取当前页码
    page = request.args.get('page', 1, type=int)
    per_page = 10  # 每页显示10条记录

    # 构建查询语句
    event_sql = "SELECT * FROM events where status = 0"
    total_sql = "SELECT COUNT(*) AS total_count FROM events where status = 0"

    # 使用分页函数获取数据和分页信息
    events, pagination = admin_service.paginate_results(total_sql, event_sql, page, per_page)

    # 获取所有分类
    categories = admin_service.get_all_categories()

    # 渲染模板，并将分页数据传递给模板
    return render_template("admin/event/event_list.html", events=events, categories=categories, pagination=pagination)


@admin_bp.route('/cancel_event', methods=['POST'])
def cancel_event():
    data = request.json
    event_id = data.get('event_id')
    status = data.get('status')
    admin_service.cancel_event(event_id,status)
   
    return jsonify({"message": "Event status updated successfully"}), 200


@admin_bp.route('/filter_events', methods=['GET', 'POST'])
def filter_events():
    page = request.args.get('page', 1, type=int)  # 获取当前页码
    per_page = 10  # 每页显示的记录数
    
    search = request.form.get('search')
    filter_type = request.form.get('filter')
    category = request.form.get('category')

    # 构建查询语句
    query = "SELECT * FROM events WHERE 1=1 and status = 0 "
    
    if search:
        if filter_type == 'location':
            query += f" AND location LIKE '%{search}%'"
        elif filter_type == 'date':
            query += f" AND date LIKE '%{search}%'"
    
    if category:
        query += f" AND category_id = '{category}'"

    # 获取总记录数的SQL
    total_sql = "SELECT COUNT(*) AS total_count FROM events WHERE 1=1 and status = 0 "
    if search:
        if filter_type == 'location':
            total_sql += f" AND location LIKE '%{search}%'"
        elif filter_type == 'date':
            total_sql += f" AND date LIKE '%{search}%'"
    
    if category:
        total_sql += f" AND category_id = '{category}'"
    
    # 调用分页函数
    events, pagination = admin_service.paginate_results(total_sql, query, page, per_page)
    
    categories = admin_service.get_all_categories()
    
    return render_template('admin/event/event_list.html', 
                           events=events, 
                           categories=categories, 
                           pagination=pagination)


@admin_bp.route('/event_detail/<int:id>', methods=(['GET','POST']))
def event_detail(id):
    event_detail = admin_service.get_event(id)
    return render_template('admin/event/event_detail.html', event=event_detail)


@admin_bp.route('/edit_event/<int:id>', methods=['GET','POST'])
def edit_event(id):
    categories = admin_service.get_all_categories()
    event = admin_service.get_event(id)
    if request.method == 'POST':
        name = request.form['name']
        description=request.form['description']
        location=request.form['location']
        date=request.form['date']
        end_date=request.form['end_date']
        intro = request.form['intro']
        category_id=request.form['category_id']
        image = request.files['images']
        img = request.form['image']
        if image:
            image.save('static/images/event/' + image.filename)
            image_name= '/static/images/event/'+ image.filename
        else:
            image_name = img
        admin_service.edit_event(id,name, description, location, date,end_date,category_id,intro,image_name)
        flash("Created event successful")
        return redirect(url_for('admin.event_management'))
    return render_template("admin/event/edit_event.html",categories=categories,event=event)

controllers/event_controller.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, flash
from flask_login import login_required, current_user
from services import event_service 
from models.event_model import Event  
from app import db
from config import setting
from models.event_registration_model import EventRegistration

event_bp = Blueprint('event', __name__)





@event_bp.route('/event_management', methods=['GET'])
@login_required
def event_management():
    page = request.args.get('page', 1, type=int)
    category = request.args.get('category', '')
    search = request.args.get('search', '')
    filter_type = request.args.get('filter', '')
    user_id = current_user.id

    # 构建基础查询语句
    base_query = f"""
    SELECT 
    e.*,
    CASE 
        WHEN e.author_id = '{user_id}' THEN 1
        WHEN er.user_id = '{user_id}' THEN 2
        ELSE 0
    END AS if_my,
    CASE 
        WHEN f.event_id IS NOT NULL THEN 1
        ELSE 0
    END AS if_f
FROM 
    events e
LEFT JOIN 
    event_registrations er ON e.id = er.event_id AND er.user_id = '{user_id}'
LEFT JOIN 
    favorites f ON e.id = f.event_id AND f.user_id = '{user_id}'  -- 加入判断是否在favorite表中
WHERE 
    1=1 and e.status = 0
    """
    total_sql = f"""SELECT COUNT(*) AS total_count FROM ({base_query}) AS total"""

    # 添加搜索和过滤条件
    if search:
        if filter_type == 'location':
            base_query += " AND e.location LIKE '%{}%'".format(search)
        elif filter_type == 'date':
            base_query += " AND e.date LIKE '%{}%'".format(search)

    if category:
        base_query += " AND e.category_id = {}".format(category)

    # 添加排序条件
    base_query += " ORDER BY e.id DESC"

    # 使用分页方法
    items, pagination = event_service.paginate_results(total_sql, base_query, page, 20)

    return render_template('front/event/event_list.html', events=items, categories=event_service.get_categories(), pagination=pagination)




@event_bp.route('/event_detail/<int:id>', methods=['GET'])
@login_required
def event_detail(id):
    event = event_service.get_event_by_id(id,current_user.id)
    return render_template("front/event/event_detail.html",event = event)


@event_bp.route('/create_event', methods=['GET','POST'])
@login_required
def create_event():
    categories = event_service.get_categories()
    if request.method == 'POST':
        name = request.form['name']
        description=request.form['description']
        location=request.form['location']
        date=request.form['date']
        end_date=request.form['end_date']
        intro = request.form['intro']
        category_id=request.form['category_id']
        image = request.files['image']
       
        if image:
            image.save('static/images/event/' + image.filename)
            image_name= '/static/images/event/'+ image.filename
        else:
            image_name = setting.default_image
        event_service.create_event(name, description, location, date,end_date,category_id,intro,image_name,current_user.id)
        flash("Created event successful")
        return redirect(url_for('event.event_management'))
    return render_template("front/event/create_event.html",categories=categories)



@event_bp.route('/edit_event/<int:id>', methods=['GET','POST'])
@login_required
def edit_event(id):
    categories = event_service.get_categories()
    event = event_service.get_event_by_id(id,current_user.id)
    if request.method == 'POST':
        name = request.form['name']
        description=request.form['description']
        location=request.form['location']
        date=request.form['date']
        end_date=request.form['end_date']
        intro = request.form['intro']
        category_id=request.form['category_id']
        
        image = request.files['image']
        if image:
            image.save('static/images/event/' + image.filename)
            image_name= '/static/images/event/'+ image.filename
        else:
            image_name = setting.default_image
        event_service.update_event(name, description, location, date,end_date,category_id,intro,image_name,id)
        return redirect(url_for('event.event_management'))
    return render_template("front/event/edit_event.html",event = event,categories=categories)

@event_bp.route('/event/<int:event_id>', methods=['PUT'])
def update_event_info(event_id):
    data = request.json
    updated_event = event_service.update_event(
        event_id,
        name=data.get('name'),
        description=data.get('description'),
        location=data.get('location'),
        date=data.get('date'),
        category_id=data.get('category_id')
    )
    if updated_event:
        return jsonify(updated_event.serialize()), 200
    return jsonify({"error": "Event not found"}), 404

@event_bp.route('/event/<int:event_id>', methods=['DELETE'])
def delete_event_info(event_id):
    deleted_event = event_service.delete_event(event_id)
    if deleted_event:
        return jsonify({"message": "Event deleted successfully"}), 200
    return jsonify({"error": "Event not found"}), 404



@event_bp.route('/favorite_event', methods=['GET'])
@login_required
def favorite_event():
    categories = event_service.get_categories()
    page = request.args.get('page', 1, type=int)
    category = request.args.get('category', '')
    search = request.args.get('search', '')
    filter_type = request.args.get('filter', '')
    user_id = current_user.id

    # 构建基础查询语句
    base_query = f"""
    SELECT 
        e.*
    FROM 
        events e
    JOIN 
        favorites f ON e.id = f.event_id AND f.user_id = '{user_id}'
    WHERE 
        e.author_id != '{user_id}' and e.status = 0
    """

    # 构建计算总记录数的查询
    total_sql = f"""SELECT COUNT(*) AS total_count FROM ({base_query}) AS total"""

    # 添加搜索和过滤条件
    if search:
        if filter_type == 'location':
            base_query += f" AND e.location LIKE '%{search}%'"
        elif filter_type == 'date':
            base_query += f" AND e.date LIKE '%{search}%'"

    if category:
        base_query += f""" AND e.category_id = '{category}'"""

    # 添加排序条件
    base_query += " ORDER BY e.id DESC"

    # 使用分页方法
    items, pagination = event_service.paginate_results(total_sql, base_query, page, 12)

    return render_template('front/event/favorite_event.html', events=items, categories=categories, pagination=pagination)


@event_bp.route('/event_register/<int:id>', methods=['POST'])
@login_required 
def event_register(id):
    event = Event.query.get_or_404(id) 
    if event:
        registration = EventRegistration(user_id=current_user.id, event_id=event.id)
        db.session.add(registration)
        db.session.commit()
        flash('Successfully registered for the event!')
        return redirect(url_for('event_bp.event_detail', event_id=event.id))
    flash('Event not found!')
    return redirect(url_for('home'))



@event_bp.route('/quit_event', methods=['POST'])
@login_required
def quit_event():
    data = request.json
    event_id = data.get('event_id')
    event_service.delete_register(event_id, current_user.id)
    return jsonify({'success': True}), 200

@event_bp.route('/add_favorite/<int:id>', methods=['POST'])
@login_required
def add_favorite(id):
   
    event_service.add_favorite(id, current_user.id)
    return jsonify({'success': True}), 200

@event_bp.route('/delete_favorite/<int:id>', methods=['POST'])
@login_required
def delete_favorite(id):
   
    event_service.delete_favorite(id, current_user.id)
    return jsonify({'success': True}), 200

@event_bp.route('/join_event', methods=['POST'])
@login_required
def join_event():
    data = request.json
    event_id = data.get('event_id')
    event_service.add_register(event_id, current_user.id)
    return jsonify({'success': True}), 200



@event_bp.route('/offline/<int:id>', methods=['POST'])
@login_required
def offline(id):
   
    event_service.update_event_status(id,1)
    return jsonify({'success': True}), 200

@event_bp.route('/online/<int:id>', methods=['POST'])
@login_required
def online(id):
    event_service.update_event_status(id,0)
    return jsonify({'success': True}), 200


@event_bp.route('/my_event', methods=['GET'])
@login_required
def my_event():
    categories = event_service.get_categories()
    page = request.args.get('page', 1, type=int)
    category = request.args.get('category', '')
    search = request.args.get('search', '')
    filter_type = request.args.get('filter', '')
    user_id = current_user.id  # 使用 Flask-Login 获取当前用户ID

    # 构建基础查询语句
    base_query = f"""
    SELECT 
        e.*
    FROM 
        events e
    WHERE 
        e.author_id = '{user_id}' and e.status = 0
    """

    # 构建计算总记录数的查询
    total_sql = f"""SELECT COUNT(*) AS total_count FROM ({base_query}) AS total"""

    # 添加搜索和过滤条件
    if search:
        if filter_type == 'location':
            base_query += f" AND e.location LIKE '%{search}%'"
        elif filter_type == 'date':
            base_query += f" AND e.date LIKE '%{search}%'"

    if category:
        base_query += f""" AND e.category_id = '{category}'"""

    # 添加排序条件
    base_query += " ORDER BY e.id DESC"

    # 使用分页方法
    items, pagination = event_service.paginate_results(total_sql, base_query, page, 12)

    return render_template('front/event/my_event.html', events=items, categories=categories, pagination=pagination)



@event_bp.route('/event_schedule')
@login_required
def event_schedule():
    return render_template('front/event/event_dashboard.html')



@event_bp.route('/calendar_events')
def calendar_events():
    rows = event_service.query_workshop_cal()
   
    resp = jsonify({'success' : 1, 'result' : rows })	# 转化为，，，便于数据展示
    resp.status_code = 200
    return resp

templates/front/event/create_event.html
{% extends 'front/base.html' %}

{% block title %}Create Event - Community Event Planner{% endblock %}

{% block content %}
<section id="banner" style="background-image:url(/static/images/background-img.jpg);">
    <div class="container padding-medium-2">
        <div class="hero-content ">
            <h2 class="display-2 fw-semibold">Create New Event</h2>
            <nav class="breadcrumb">
                <a class="breadcrumb-item text-muted nav-link" href="{{url_for('admin.home')}}">Home</a>
                
                <span class="breadcrumb-item active" aria-current="page">Create New Event</span>
            </nav>
        </div>
    </div>
</section>
<section id="course" class="padding-medium">
    <div class="container">
        <form method="POST" action="{{ url_for('event.create_event') }}" id="eventForm" enctype="multipart/form-data">
            <div class="form-group mb-3">
                <label for="name">Event Name:</label>
                <input type="text" id="name" name="name" class="form-control" required>
            </div>
            <div class="form-group mb-3">
                <label for="intro">Introduction:</label>
                <textarea id="intro" name="intro" class="form-control" required></textarea>
            </div>
            <div class="form-group mb-3">
                <label for="description">Description:</label>
                <textarea id="description" name="description" class="form-control" required></textarea>
            </div>
            <div class="form-group mb-3">
                <label for="location">Location:</label>
                <input type="text" id="location" name="location" class="form-control" required>
            </div>
            <div class="form-group mb-3">
                <label for="date">Date:</label>
                <input type="datetime-local" id="date" name="date" class="form-control" required>
            </div>
        
            <div class="form-group mb-3">
                <label for="end_date">End Date:</label>
                <input type="datetime-local" id="end_date" name="end_date" class="form-control" required>
            </div>
            <div class="form-group mb-3">
                <label for="img">Image:</label>
                <input type="file" id="image" name="image" pattern=".*\.(jpg|jpeg|png|gif)$" title="Please upload a valid image file name (jpg, jpeg, png, gif)">
            </div>
            <div class="form-group mb-3">
                <label for="category_id">Category:</label>
                <select id="category_id" name="category_id" class="form-control">
                    <option value="0">Please choose one category</option>
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-success">Create Event</button>
        </form>
    </div>
</section>
<script>
    // 设置日期时间选择器的最小值为当前日期时间
    document.addEventListener('DOMContentLoaded', function() {
        var dateInput = document.getElementById('date');
        var endDateInput = document.getElementById('end_date');
        
        var now = new Date();
        var year = now.getFullYear();
        var month = String(now.getMonth() + 1).padStart(2, '0');
        var day = String(now.getDate()).padStart(2, '0');
        var hours = String(now.getHours()).padStart(2, '0');
        var minutes = String(now.getMinutes()).padStart(2, '0');
        
        var minDateTime = year + '-' + month + '-' + day + 'T' + hours + ':' + minutes;
        
        dateInput.setAttribute('min', minDateTime);
        endDateInput.setAttribute('min', minDateTime);
    });

    // 验证 category_id 是否被选择的 JS 代码
    document.getElementById('eventForm').addEventListener('submit', function(event) {
        var categorySelect = document.getElementById('category_id');
        
        if (categorySelect.value === '0') {
            event.preventDefault();  // 阻止表单提交
            alert('Please choose a category before submitting the form.');
        }
    });
</script>
{% endblock %}

templates/front/event/event_detail.html
{% extends 'front/base.html' %}

{% block title %}Event Dashboard - Community Event Planner{% endblock %}

{% block content %}
<section id="banner" style="background-image:url(/static/images/background-img.jpg);">
    <div class="container padding-medium-2">
        <div class="hero-content ">
            <h2 class="display-2 fw-semibold">Event <span class="text-primary">Details</span></h2>
            <nav class="breadcrumb">
                <a class="breadcrumb-item text-muted nav-link" href="{{url_for('admin.home')}}">Home</a>

                <span class="breadcrumb-item active" aria-current="page">Event Details</span>
            </nav>
        </div>
    </div>
</section>

<div class="container padding-medium">
    <h2 class="display-5 fw-semibold">{{event.name}}</h2>
    <div class="d-md-flex mt-2 mb-5">
        <div><iconify-icon icon="lets-icons:date-today" class="text-primary fs-5 pt-1"
                style="vertical-align: sub;"></iconify-icon> {{event.date}}</div>
        <div class=" align-self-end fs-5">&nbsp; | &nbsp;</div>
        <div><iconify-icon icon="lets-icons:date-today" class="text-primary fs-5 pt-1"
                style="vertical-align: sub;"></iconify-icon> {{event.end_date}}</div>
        <div class=" align-self-end fs-5">&nbsp; | &nbsp;</div>
        <div><iconify-icon icon="mdi:location" class="text-primary fs-5 pt-1"
                style="vertical-align: sub;"></iconify-icon> {{event.location}}</div>
    </div>
    <img src="{{event.img}}" alt="single-post" class="img-fluid">
  
</div>

<div class="post-wrap">
    <div class="container">
        <div class="row g-md-5">
            <main class="post-grid col-md-8">
                <div class="post-description">
                    {{event.intro}}
                </div>
                <div class="post-description">
                    {{event.description}}
                </div>

                <div class="mt-5">
                    <h4>Event Location</h4>
                    <div class="mb-4 fs-6">
                        <iconify-icon icon="mdi:location" class="text-primary fs-5" style="vertical-align: sub;"></iconify-icon>
                        {{event.location}}
                    </div>
                </div>                
                {%if event.registration_status == '0' %}
                <a href="#" onclick="quitEvent({{ event.id }})"
                    class=" btn btn-outline-dark text-capitalize me-2 px-4 py-3">Cancel</a>
                {%else%}
                <a href="#" onclick="joinEvent({{ event.id }})"
                    class=" btn btn-outline-dark text-capitalize me-2 px-4 py-3">Join</a>
                {%endif%}
            </main>

        </div>
    </div>
</div>
<script>

    function joinEvent(eventId) {
        $.ajax({
            url: "{{ url_for('event.join_event') }}",
            type: "POST",
            contentType: "application/json",
            data: JSON.stringify({ "event_id": eventId }),
            success: function (response) {
                if (response.success) {
                    alert('You have successfully joined the event.');
                    location.reload();
                    // 更新页面状态
                } else {
                    alert('Failed to join the event.');
                }
            },
            error: function (xhr, status, error) {
                console.error('Error joining event:', error);
                alert('Failed to join the event.');
            }
        });
    };
    function quitEvent(eventId) {
        $.ajax({
            url: "{{ url_for('event.quit_event') }}",
            type: "POST",
            contentType: "application/json",
            data: JSON.stringify({ "event_id": eventId }),
            success: function (response) {
                if (response.success) {
                    alert('You have successfully quit the event.');
                    location.reload();
                    // 更新页面状态
                } else {
                    alert('Failed to quit the event.');
                }
            },
            error: function (xhr, status, error) {
                console.error('Error quitting event:', error);
                alert('Failed to quit the event.');
            }
        });
    };
</script>

{% endblock %}

templates/front/event/my_event.html
{% extends 'front/base.html' %}

{% block title %}Event List - Community Event Planner{% endblock %}

{% block content %}


<section id="course" class="padding-medium">
  <div class="container">

    <div class="text-center mb-5">
      <h2 class="display-5 fw-semibold"><span class="text-primary">Events List</span></h2>
    </div>
    <div class=" row">
      <form action="{{ url_for('event.my_event') }}" method="GET">
        <div class="row mb-4">
          <div class="col-md-4">
            <input type="text" id="search-input" name="search" class="form-control"
              placeholder="Search by Location or Date" value="{{ request.args.get('search', '') }}">
          </div>
          <div class="col-md-4">
            <select id="location-date-select" name="filter" class="form-control">
              <option value="location" {% if request.args.get('filter')=='location' %}selected{% endif %}>Location
              </option>
              <option value="date" {% if request.args.get('filter')=='date' %}selected{% endif %}>Date</option>
            </select>
          </div>
          <div class="col-md-4">
            <select id="category-select" name="category" class="form-control">
              <option value="">Filter by Category</option>
              {% for category in categories %}
              <option value="{{ category.id }}" {% if request.args.get('category')==category.id %}selected{% endif %}>{{
                category.name }}</option>
              {% endfor %}
            </select>
          </div>
        </div>

        <div class="text-center mb-4">
          <button type="submit" class="btn btn-primary me-2">Filter</button>
          <a href="{{ url_for('event.my_event') }}" class="btn btn-secondary">Reset</a>
        </div>
      </form>
    </div>

    
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Event Name</th>
              <th>Date</th>
              <th>End Date</th>
              <th>Location</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% if events %}
            {% for event in events %}
            <tr>
              <td>{{ event.name }}</td>
              <td>{{ event.date }}</td>
              <td>{{ event.end_date }}</td>
              <td>{{ event.location }}</td>
              <td>{{ event.if_my }}</td>
              <td>
                <a href="{{ url_for('event.event_detail', id=event.id) }}" class="btn btn-outline-dark text-capitalize"
                  target="_blank">View</a>
                {%if event.status == '0'%}
                <a href="#" class="btn btn-outline-dark text-capitalize" onclick="setEventOffline({{ event.id }})"
                  id="cancel-event" data-event-id="{{ event.id }}">Offline</a>
                {%elif event.status == '1'%}

                <a href="#" class="btn btn-outline-dark text-capitalize" onclick="setEventOnline({{ event.id }})"
                  id="online-event" data-event-id="{{ event.id }}">Online</a>
                {%endif%}
                <a href="{{ url_for('event.edit_event', id=event.id) }}"
                  class="btn btn-outline-dark text-capitalize">Edit</a>
              </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
              <td colspan="5" class="text-center">No events found.</td>
            </tr>
            {% endif %}
          </tbody>
        </table>
      </div>
      <div class="pagination-area mt-15 mb-sm-5 mb-lg-0">
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-start">
            {% if pagination.page > 1 %}
            <li class="page-item">
              <a class="page-link"
                href="{{ url_for('event.my_event', page=pagination.page - 1, category=request.args.get('category'), search=request.args.get('search')) }}">Previous</a>
            </li>
            {% endif %}

            {% for page_num in range(1, pagination.num_pages + 1) %}
            <li class="page-item">
              <a class="page-link"
                href="{{ url_for('event.my_event', page=page_num, category=request.args.get('category'), search=request.args.get('search')) }}">{{
                page_num }}</a>
            </li>
            {% endfor %}

            {% if pagination.page < pagination.num_pages %} <li class="page-item">
              <a class="page-link"
                href="{{ url_for('event.my_event', page=pagination.page + 1, category=request.args.get('category'), search=request.args.get('search')) }}">Next</a>
              </li>
              {% endif %}
          </ul>
        </nav>
      </div>
    


  </div>
</section>
<script>

  function setEventOffline(eventId) {
    console.log("Clicked event ID:", eventId); // 输出ID以检查
    if (!eventId || isNaN(eventId)) {
      console.error("Invalid event ID");
      return;
    }

    const url = `/event/offline/${eventId}`;
    console.log("Generated URL:", url); // 输出URL以检查

    fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({})
    })
      .then(response => {
        if (response.ok) {
          console.log("Event set to offline successfully");
          alert('Event set to offline successfully!'); // 显示成功消息
          location.reload(); // 刷新页面
        } else {
          response.json().then(data => console.error("Error response:", data));
        }
      })
      .catch(error => console.error("Fetch error:", error));
  }
  function setEventOnline(eventId) {
    console.log("Clicked event ID:", eventId); // 输出ID以检查
    if (!eventId || isNaN(eventId)) {
      console.error("Invalid event ID");
      return;
    }

    const url = `/event/online/${eventId}`;
    console.log("Generated URL:", url); // 输出URL以检查

    fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({})
    })
      .then(response => {
        if (response.ok) {
          console.log("Event set to online successfully");
          alert('Event set to online successfully!'); // 显示成功消息
          location.reload(); // 刷新页面
        } else {
          response.json().then(data => console.error("Error response:", data));
        }
      })
      .catch(error => console.error("Fetch error:", error));
  }


</script>
{% endblock %}